### ISSUE TITLE
Fail to compile -- Using the specific lvgl version to compile successfully

### ISSUE THREAD

**Issue by betamoojw** [fvanroie/hasp-lvgl#10]
As the lvgl is evaluating and iterating causing some incompatible issues. As stated `lib_deps =
    https://github.com/littlevgl/lvgl.git ;lvgl@6.1.2 - Not in library yet` in the platformio.ini, modify it to `https://github.com/littlevgl/lvgl.git#v6.1.2 ;lvgl@6.1.2 - Not in library yet` and then compile successfully.

**Comment by fvanroie** [comment]
Which branch of hasp-lvgl did you upload?

I'm working on polishing up the repository and including a more streamlined installation, with pre-compiled binaries for ESP32/8266. So this shouldn't be an issue in the future.

**Comment by betamoojw** [comment]
The branch of hasp-lvgl used in my case is the default (0.0.11).
As mentioned above, I modified `lib_deps = https://github.com/littlevgl/lvgl.git#v6.1.2  ;lvgl@6.1.2` with specified lvgl version and then compile and run it successfully on my hardware.

**Comment by fvanroie** [comment]
I made the update to v6.1.2 in the 0.0.11 branch. This should fiw that complile issue.
In the near future, the new default branch will switch to 0.2.0 as that is the most recent and active branch being developed.
