### ISSUE TITLE
Arc min not respected if over 100

### ISSUE THREAD

**Issue by nagyrobi** [fvanroie/hasp-lvgl#103]
You want to have an arc with `"min":120,"max":350` but you notice that in reality the arc goes from 0 to 350 instead.
To reproduce:
- `"min":10,"max":20` - OK
- `"min":80,"max":350` - OK
- `"min":120,"max":200` - Not OK, it will go from 0 to 350.

It looks like min doesn't like values above 100.

**Comment by arovak** [comment]
passing the max value before the min value will make the arc set and return the correct values.
```"max":200,"min":120```

**Comment by nagyrobi** [comment]
Is this on purpose? documented somewhere?

**Comment by arovak** [comment]
I believe this is resolved, can you confirm it works as expected now?

**Comment by nagyrobi** [comment]
Still testing

**Comment by nagyrobi** [comment]
It's OK now, thanks.
