### ISSUE TITLE
Fail to compile with <pio\libdeps\esp12e-st7735\Ethernet\src\Ethernet.cpp:87:24: error: 'class IPAddress' has no member named '_address'   W5100.setIPAddress(ip._address.bytes);>

### ISSUE THREAD

**Issue by betamoojw** [fvanroie/hasp-lvgl#11]
Check the platform.ini and found out for [env:esp12e-st7735] using the 
`lib_deps =
    ${env.lib_deps}
    Ethernet@<2.0.0`

Generally, Ethernet lib is applicable for W5100/5500 ethernet chip. That being said, for esp12e in our case, we should ignore this lib.

Append as below 
`; -- Library options -------------------------------
lib_deps =
    ${env.lib_deps}
    Ethernet@<2.0.0

lib_ignore =
  Ethernet`

Then compile successfully.

**Comment by fvanroie** [comment]
That library can indeed be omitted from the esp12e environment.
