### ISSUE TITLE
Remove file from SPIFFS

### ISSUE THREAD

**Issue by 12christiaan** [fvanroie/hasp-lvgl#14]
Not a issue, more a question.
While going over the code, i saw this option.
http://192.168.1.118/list?dir=
It will list all the file on the SPIFFS.
I am testing some different fonts and font size, now the SPIFFS is running full.
and the only option i found to remove them is to flash a empty image over the SPIFFS. 

did you build some other (hidden) option to remove file's?

**Comment by fvanroie** [comment]
There is no _native_ file browser provided yet, as this currently is low on the priority list.

However, you can upload the 3KB `edit.htm.gz` file from the ESP32 FSBrowserrepository to SPIFFS
from: https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/examples/FSBrowser/data/edit.htm.gz

When the  `edit.htm.gz` file is present you will see an additional File Browser button on the Main Webpage:
![image](https://user-images.githubusercontent.com/15969459/97497227-78de6280-196a-11eb-92d9-04de2db5818f.png)

Using that webpage, you can right-click and delete files:

![image](https://user-images.githubusercontent.com/15969459/97497310-99a6b800-196a-11eb-929f-e3c7b6642f54.png)

**Comment by 12christiaan** [comment]
Perfect, 
that works perfectly.

**Comment by fvanroie** [comment]
Closing this issue and added the solution to the FAQ page of the Wiki.
