### ISSUE TITLE
Allow offline mode

### ISSUE THREAD

**Issue by fvanroie** [fvanroie/hasp-lvgl#28]
Currently the switchplate needs to be connected to wifi & mqtt, otherwise it will reboot after an extended time-out.

With local gpios connected in groups, it should be possible to use the switch in an offline mode, with only local gpio functions and GUI.

**Comment by fvanroie** [comment]
> it should still let you access the page after a touch because you might have groups defined

**Comment by nagyrobi** [comment]
+1 for this. Moreover, have a way to display status/warning and perhaps a way to programatically disable or hide certain controls based on offline status.
