### ISSUE TITLE
dropdown selection does not respect text_font size

### ISSUE THREAD

**Issue by blakadder** [fvanroie/hasp-lvgl#43]
![image](https://user-images.githubusercontent.com/5904370/104070469-3e653180-5207-11eb-8b4b-53523bbcd1b8.png)

object setting `{"objid":50,"id":6,"x":55,"y":150,"w":150,"options":"Coffee\nGreen Tea\nOolong Tea\nPu-Erh Tea\n","text_font":12}`

default font is set to very large so it renders other options using it instead of text_font

**Comment by fvanroie** [comment]
I think this is related to the custom HASP theme. Does it happen with Material too?

**Comment by blakadder** [comment]
That was the material theme used, its my default goto

**Comment by fvanroie** [comment]
OK I'll look into this a bit further

**Comment by htvekov** [comment]
I'm experiencing same issue using default font
hasp Dark theme (hasp v0.3.3 - ESP32)

object:`{"obj":"dropdown","id":25,"page":4,"x":1,"y":1,"w":239,"h":319,"bg_color":"#000000","bg_opa":255,"border_color":"#C7BAA7","border_width":1,"val":2,"options":"TEST1\nTEST2\n","txt":"SOURCE","text_color":"#FFAC00","text_font":22}`

![image](https://user-images.githubusercontent.com/45469813/106971750-d8a98e00-674f-11eb-96cf-4b2fd8fcc4fb.png)

**Comment by fvanroie** [comment]
This issue should now be fixed.
