### ISSUE TITLE
M5Stack Core 2 support

### ISSUE THREAD

**Issue by gerard33** [fvanroie/hasp-lvgl#66]
Will this software also work with the M5Stack Core 2 which is ESP32 based?
https://m5stack.com/products/m5stack-core2-esp32-iot-development-kit

The display is 2.0"@320*240 ILI9342C with a FT6336U touch screen.

I have one currently using https://github.com/sieren/Homepoint on the Core 2 but that’s not working as expected for the Core 2 at the moment.

**Comment by fvanroie** [comment]
There is basic support for the M5strack core2 in the source code. We have not released any binaries for this platform yet.
Some parts are not ready for the M5stack core2, but you can certainly try it out and provide your feedback.

To get your device flashed, you should install Visual Studio Code with PlarformIO and build the configuration named `m5stack-core2`.
