### ISSUE TITLE
Feature request: with screen off, first touch should just wake screen

### ISSUE THREAD

**Issue by nagyrobi** [fvanroie/hasp-lvgl#80]
After Long Idle, screen turns off. If I touch the screen to wake it, the object underneath will also react. This is a problem as the user might touch in the wrong area without first seeing the screen, causing undesired effects. 

It would be nice to have an option/setting which enabled, at touch would check first if the screen is off and if it is, just wake it and exit routine/function without touching the objects.

**Comment by fvanroie** [comment]
This request has come up before and will be included in one way or another...

**Comment by fvanroie** [comment]
This is now implemented in the 0.4.0-dev branch.

**Comment by nagyrobi** [comment]
Works, excellent, thank you!

**Comment by nagyrobi** [comment]
No it doesn't... so reopening...

**Comment by fvanroie** [comment]
Are you setting dim to 0 instead of setting light to off?

The wakeup touch enables the backlight, so reverting to the previous dim level.
If the dim level is 0, the backlight will turn on to the level 0...

**Comment by nagyrobi** [comment]
I'm using thh HA component...

**Comment by nagyrobi** [comment]
No that's not the problem. The problem is that if I touch the screen it wakes up normally, but it also clicks the object.

**Comment by fvanroie** [comment]
Wakeup touch is only enabled/disabled when using `light off/on` commands. You should see it appear in the log:

![image](https://user-images.githubusercontent.com/15969459/111326839-2ed1f100-866d-11eb-82b2-576aa2da46d7.png)

It seems you are just setting dim to 0, which will not enable wakeup touch.

**Comment by fvanroie** [comment]
Is this still an issue?

**Comment by nagyrobi** [comment]
Hopefully not. I expeience strange touch things occasionally but i think not related to this.
